-- Digital Command — tracks which AI provider (Anthropic Claude vs. Kimi/
-- Moonshot AI) generated each ai_usage_events row, so the Cost/Profit
-- Dashboard (app/admin/costs) can attribute spend correctly once Kimi is a
-- genuine second option (see ARCHITECTURE.md — "AI Provider Abstraction").
--
-- Row-level, not column-level: ai_usage_events_select_admin/_insert
-- (0017_phase7_rls.sql) are plain row policies with no column list, so they
-- already cover this new column without any RLS change — confirmed by
-- reading that file before writing this migration.
--
-- default 'anthropic' is not just a safe default, it's factually correct —
-- every row inserted before this migration exists was generated by Claude,
-- since Kimi didn't exist as an option yet.
alter table public.ai_usage_events
  add column provider text not null default 'anthropic'
  check (provider in ('anthropic', 'kimi'));
